# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BOLT_SSI <- function(X, y, extra_pairs = -1L, code_num = 3L, thread_num = 4L) {
    .Call('_BOLTSSIRR_BOLT_SSI', PACKAGE = 'BOLTSSIRR', X, y, extra_pairs, code_num, thread_num)
}

BOLT_SSI_RR <- function(X, y, extra_pairs = -1L, code_num = 3L, nLambda = 100L, thread_num = 1L) {
    .Call('_BOLTSSIRR_BOLT_SSI_RR', PACKAGE = 'BOLTSSIRR', X, y, extra_pairs, code_num, nLambda, thread_num)
}

CV_BOLT_SSI_RR <- function(X, y, extra_pairs = -1L, code_num = 3L, nfold = 10L, nLambda = 100L, thread_num = 4L) {
    .Call('_BOLTSSIRR_CV_BOLT_SSI_RR', PACKAGE = 'BOLTSSIRR', X, y, extra_pairs, code_num, nfold, nLambda, thread_num)
}

rcpp_hello <- function() {
    .Call('_BOLTSSIRR_rcpp_hello', PACKAGE = 'BOLTSSIRR')
}

